### PR TITLE
Refs #474 -- Added MixedAccounting to general/build/smart-contracts/contract-security

### PR DESCRIPTION
**Pull request by jackleeio**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: #474  (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

- - -
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/574)

### CODE REVIEW

**Review by darwintree — CHANGES_REQUESTED** [review]
I think the content is generally good. Here are some questions and suggestions
1. Is the title `mixed accounting` not a general term? If not, I think the title shall be altered to reflect the article content appropriately, for example, `balance accounting`.
2. The mixed acocunting would only result in actual balance greater than the balance as local state variable, and this would not bring about securtiy issues. This idea is already implicitly conveyed in the article. But I would recommend explicitly stating it and then highlight the security issues result from the incorrect assumptions rather than the unexpected more balance itself.
3. (Optional) There are some handler functions for ERCxxx tokens, e.g. `onERC20Recieved`, `onERC721Received`. These handler can be mentioned in the article body.

**Review by darwintree — APPROVED** [review]

**Review by darwintree — CHANGES_REQUESTED** [review]
It seems the title stays unchanged. Is this a specific term or how about your idea about current title? We can discuss it here

**Comment by jackleeio** [comment]
`mixed accounting` is not a specific term. I want to express that mixing two accounting methods in a contract will bring some potential security issues, so I think it is better to use `mixed accounting` than `balance accounting`.

**Comment by darwintree** [comment]
> `mixed accounting` is not a specific term. I want to express that mixing two accounting methods in a contract will bring some potential security issues, so I think it is better to use `mixed accounting` than `balance accounting`.

From my perspective, at least the title would let reader have a basic concept about the article content. As for `mixed accounting`, readers would not know or expect what the article is about. It's ok not to adobt the proposed example `balance accounting` but I don't think `mixed accounting` is a good title

**Review by darwintree — APPROVED** [review]

**Pull request merged**
