### PR TITLE
Refs #474 -- Add "Ways Lenders Lose Out in DeFi Lending Protocols" to Contract Security

### PR DESCRIPTION
**Pull request by jackleeio**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: #474 (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

- - -
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/664)

### CODE REVIEW

**Review by darwintree — COMMENTED** [review]
I think the content is generally correct but I would want to know the target audience of this article and the purpose of the article.
For current version, it seems that this article is written as if it were for lending protocol designers and developers. However, lending protocols are quite delicate and complex to design and implement. And I don't think our site is that important enough for them to refer to.
I think the content is good enough, but I would know your original idea of the target audience of this article so it can be made clear who need to read it

**Comment by jackleeio** [comment]
I consider the development of lending protocols to be a part of smart contract development. This article provides a summary of common issues, with some preventive measures mentioned in previous articles. For beginners or intermediate developers who may encounter lending protocol development, this article can be helpful.

**Comment by darwintree** [comment]
> I consider the development of lending protocols to be a part of smart contract development. This article provides a summary of common issues, with some preventive measures mentioned in previous articles. For beginners or intermediate developers who may encounter lending protocol development, this article can be helpful.

I agree that these common issues are useful. However, similar to [Why is it wrong to *implement* myself a known, published, widely believed to be secure crypto algorithm?](https://security.stackexchange.com/questions/209652/why-is-it-wrong-to-implement-myself-a-known-published-widely-believed-to-be), I think it never a good practice for beginners as well as intermediate developers to directly engage at least in the development of lending protocol itself.

**Comment by jackleeio** [comment]
> I think it never a good practice for beginners as well as intermediate developers to directly engage at least in the development of lending protocol itself. And that is why I mainly focus on the target audience

I think you misunderstood my point. The aim is not to encourage beginners or intermediate devs to directly engage in the development of lending protocols. Rather, it is to provide necessary information to devs who need it, such as those interested in understanding the security aspects of lending protocol contracts, or those wanting to develop DeFi projects on Conflux. 

This content can serve as a reference or guide to help them develop more secure DeFi applications on Conflux.

**Comment by jackleeio** [comment]
If you feel that this content is not suitable for the current context, I would want to know if it would be possible to start a new series focusing on common vulnerabilities and prevention methods related to lending or staking protocols (though some content might overlap with the current contract security series). Alternatively, I could break down the current article into several detailed parts and incorporate them into the current contract security series.

**Comment by darwintree** [comment]
> If you feel that this content is not suitable for the current context, I would want to know if it would be possible to start a new series focusing on common vulnerabilities and prevention methods related to lending or staking protocols (though some content might overlap with the current contract security series). Alternatively, I could break down the current article into several detailed parts and incorporate them into the current contract security series.

Yes, I think that is a good point and we can also give some basic introduction to these well known protocols. Besides, we can also create a folder in the general folder containing general advices or suggestions relating to blockchain security mainly for users.

**Pull request closed without merging**
