### PR TITLE
Add Deploying Upgradeable Contracts using Foundry

### PR DESCRIPTION
**Pull request by jackleeio**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: #681 (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

### CODE REVIEW

**Comment by jackleeio** [comment]
When deploying a contract to the eSpace testnet using Foundry, I encountered some issues. It keeps showing an error that there isn’t enough gas, but my account actually has sufficient CFX. The same code deploys without issues on other networks, such as Sepolia. I’m wondering if it might be a compatibility issue between Conflux eSpace and Foundry.
@darwintree  @0xn1c0

**Comment by darwintree** [comment]
> When deploying a contract to the eSpace testnet using Foundry, I encountered some issues. It keeps showing an error that there isn’t enough gas, but my account actually has sufficient CFX. The same code deploys without issues on other networks, such as Sepolia. I’m wondering if it might be a compatibility issue between Conflux eSpace and Foundry. @darwintree @0xn1c0

Will check it

**Comment by darwintree** [comment]
@jackleeio  Using the --gas-estimate-multiplier or -g option would be help. I got expected result with `forge script script/Deploy.s.sol:DeployScript --rpc-url espaceTestnet --broadcast -g 200`

**Comment by jackleeio** [comment]
> @jackleeio Using the --gas-estimate-multiplier or -g option would be help. I got expected result with `forge script script/Deploy.s.sol:DeployScript --rpc-url espaceTestnet --broadcast -g 200`

It worked, thanks!

**Comment by 0xn1c0** [comment]
> > @jackleeio Using the --gas-estimate-multiplier or -g option would be help. I got expected result with `forge script script/Deploy.s.sol:DeployScript --rpc-url espaceTestnet --broadcast -g 200`
> 
> It worked, thanks!

@jackleeio Can you please add a comment or note in the document with this indication?

**Pull request merged**
