### PR TITLE
Added Basics Page

### PR DESCRIPTION
**Pull request by 0xn1c0**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-documentation/38)

### CODE REVIEW

**Review by darwintree — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-documentation/38)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @0xn1c0)

___
*[`docs/learn/getting-started/core-space/basics.md` line 26 at r1](https://reviewable.io/reviews/conflux-chain/conflux-documentation/38#-NMwUrdg0s36mOt8vMnE:-NMwUrdh6QScmfP0CCqd:b-21nmo8) ([raw file](https://github.com/conflux-chain/conflux-documentation/blob/bad5eaff853ff66ac944fec62fde1b9fb5e9df4c/docs/learn/getting-started/core-space/basics.md#L26)):*
> ```Markdown
> Conflux introduces a staking mechanism. This mechanism also serves to construct the voting rights of Conflux decentralized governance. 
> 
> For miners who participate in mining, a certain amount of CFX for each block mined. The collateral revenue generated by the collateralized CFX is also paid to the miners to cover the cost of storage. which provides an incentive for miners to continue participating in bookkeeping, and thus ensuring security for the network. The block payout bonus consists of three parts:
> ```

Infomation about ParamsVote should be added
___
*[`docs/learn/getting-started/core-space/basics.md` line 116 at r1](https://reviewable.io/reviews/conflux-chain/conflux-documentation/38#-NMwVnI_3znBV8_WwX7j:-NMwVnI_3znBV8_WwX7k:bg7h4sv) ([raw file](https://github.com/conflux-chain/conflux-documentation/blob/bad5eaff853ff66ac944fec62fde1b9fb5e9df4c/docs/learn/getting-started/core-space/basics.md#L116)):*
> ```Markdown
> 
> 
> ### Lifecycle of a transaction
> ```

Link for the specific article should be added here. And `finalized` state should be added

**Review by 0xn1c0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-documentation/38)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @darwintree)

___
*[`docs/learn/getting-started/core-space/basics.md` line 116 at r1](https://reviewable.io/reviews/conflux-chain/conflux-documentation/38#-NMwVnI_3znBV8_WwX7j:-NNbDh4K6v2MCTqLc7E3:b-dxfgy2) ([raw file](https://github.com/conflux-chain/conflux-documentation/blob/bad5eaff853ff66ac944fec62fde1b9fb5e9df4c/docs/learn/getting-started/core-space/basics.md#L116)):*
<details><summary><i>Previously, darwintree wrote…</i></summary><blockquote>

Link for the specific article should be added here. And `finalized` state should be added
</blockquote></details>

I already added the finalized state. What article do you mean?

**Review by 0xn1c0 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-documentation/38)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @darwintree)

___
*[`docs/learn/getting-started/core-space/basics.md` line 26 at r1](https://reviewable.io/reviews/conflux-chain/conflux-documentation/38#-NMwUrdg0s36mOt8vMnE:-NNbH1P-EJhmm1dbJSns:b-896fix) ([raw file](https://github.com/conflux-chain/conflux-documentation/blob/bad5eaff853ff66ac944fec62fde1b9fb5e9df4c/docs/learn/getting-started/core-space/basics.md#L26)):*
<details><summary><i>Previously, darwintree wrote…</i></summary><blockquote>

Infomation about ParamsVote should be added
</blockquote></details>

Done.

**Review by darwintree — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-documentation/38)* status: 1 of 2 files reviewed, 2 unresolved discussions

**Pull request merged**
