### PR TITLE
Added Cookbook Tutorial

### PR DESCRIPTION
**Pull request by 0xn1c0**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://doc.confluxnetwork.org/docs/general/CONTRIBUTING#create-a-pull-request).
- [x] A relating issue is created: # (<- fill the issue number here)
- [x] **This is NOT a PR to submit translation**

- - -
This change is [Reviewable](https://reviewable.io/reviews/Conflux-Chain/conflux-documentation/511)

### CODE REVIEW

**Comment by 0xn1c0** [comment]
Based on this issue:
https://github.com/Conflux-Chain/conflux-documentation/issues/326

**Review by darwintree — CHANGES_REQUESTED** [review]
I think we should remove the remix relating content as they are already explaned in the remix article. After that, we can place this article at espace/tutorials/cookbook, and add links in Remix IDE article

**Comment by 0xn1c0** [comment]
I've made the changes based on your suggestions @darwintree . Let me know if there is any other change you suggest

**Comment by darwintree** [comment]
I think something can be added to the remix tutorial(espace/tutorials/how-to/remix) to notify readers they can find solidity source files in cookbook

**Comment by 0xn1c0** [comment]
I've added a reference to the remix tutorial as you suggested. Let me know if there is any other suggested changes.

**Review by darwintree — APPROVED** [review]

**Pull request merged**
