### PR TITLE
Added Addresses, CIPs and TreeGraph pages

### PR DESCRIPTION
**Pull request by 0xn1c0**
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-documentation/8)

### CODE REVIEW

**Review by Pana — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-documentation/8)* status: all files reviewed, 3 unresolved discussions (waiting on @0xn1c0)

___
*[`docs/build/_category_.json` line 1 at r1](https://reviewable.io/reviews/conflux-chain/conflux-documentation/8#-NC8JKxQ3w4abLeR96ws:-NC8JKxQ3w4abLeR96wt:bqtp4a1) ([raw file](https://github.com/conflux-chain/conflux-documentation/blob/a03ce2f0b4da2c154960497325481f3c50365b4f/docs/build/_category_.json#L1)):*
> ```JSON
> {
> ```

What's these files used for ? It's better not add auto-generated files to regpo
___
*[`docs/build/getting-started/addresses.md` line 9 at r1](https://reviewable.io/reviews/conflux-chain/conflux-documentation/8#-NC8Jej83k3TaCcBU0bb:-NC8Jej83k3TaCcBU0bc:bqk6fc0) ([raw file](https://github.com/conflux-chain/conflux-documentation/blob/a03ce2f0b4da2c154960497325481f3c50365b4f/docs/build/getting-started/addresses.md#L9)):*
> ```Markdown
> ## Overview
> 
> Each Conflux [account](https://hackmd.io/@thegaram/rymwcvajq) is identified by its address. When sending tokens to someone or interacting with a smart contract, you will need to know their address. You can also share your address with other people so that you can receive token transfers.
> ```

These links need to be updated when the target files have added to repo
___
*[`docs/stake/getting-started/addresses.md` line 4 at r1](https://reviewable.io/reviews/conflux-chain/conflux-documentation/8#-NC8KlZb4wixrMfrnYBI:-NC8KlZc0kKMpjvwsFpN:b-dtp3xn) ([raw file](https://github.com/conflux-chain/conflux-documentation/blob/a03ce2f0b4da2c154960497325481f3c50365b4f/docs/stake/getting-started/addresses.md#L4)):*
> ```Markdown
> sidebar_position: 1
> ---
> ```

why the addresses doc has been added to multiple folder

**Review by Pana — COMMENTED** [review]
I think we should have an 'Overview' as the first doc. And why every folder has a getting started subfolder?

> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-documentation/8#-:-NC8TY3X1vHuXEdbX2eq:b-oa9lyx)* status: all files reviewed, 2 unresolved discussions (waiting on @0xn1c0)

**Review by 0xn1c0 — COMMENTED** [review]
Made some fixes

**Review by Pana — APPROVED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/conflux-documentation/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0xn1c0)

**Pull request merged**
